#!/bin/bash
#
#

ricename=glass

echo Please enter your root/sudo password
read -s varpw


echo "$varpw" | sudo -S pacman -Syy

#installs extra base packages not included with cachy
echo "$varpw" | sudo -S pacman -S --noconfirm --needed tty-clock xclip hyprlock hyprpaper nvim rofi waybar zsh nwg-look nemo pavucontrol ttf-jetbrains-mono-nerd ttf-tinos-nerd spotify-launcher steam swayidle gimp prismlauncher obs-studio vlc shotcut wine

#installs ohmyzsh
RUNZSH=no CHSH=no KEEPZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#sets default shell to zsh
echo "$varpw" | sudo -S chsh -s "$(which zsh)" "$USER"

#creates basic directories
mkdir -p ~/Pictures
mkdir -p ~/Documents
mkdir -p ~/.icons
mkdir -p ~/.themes
mkdir -p ~/shellscripts
cp help ~/Documents
cp -R shellscripts ~/
#sets getty user for hyprlock auto login
sed -i -e "s|<user>|$USER|g" hyprlockgetty


tar -xzf doticons.tgz
tar -xzf dotthemes.tgz


rm *.tgz

zshtext=$(cat hyprlockzsh)
gettytext=$(cat hyprlockgetty)


#i want to be able to test this in a vm without it freaking out
#so i need to be able to determine if im in a vm, i figure
#the easiest way to do this is to just see if the monitor
#is Virtual-1
monname=$(hyprctl monitors all | sed '1!d' | grep Monitor | cut -d ' ' -f 2)
if [ "$monname" = "Virtual-1" ]; then
	echo "vm detected, modifying files as necessary"
		cat dotconfig/hypr/hyprland.conf.vm > dotconfig/hypr/hyprland.conf
		cat dotconfig/hypr/hyprpaper.conf.vm > dotconfig/hypr/hyprpaper.conf
		cat dotconfig/waybar/config.jsonc.vm > dotconfig/waybar/config.jsonc

else
	echo "normal system detected, proceeding normally"
	sed -i -e "s|Virtual-1|$monname|g" dotconfig/hypr/hyprpaper.conf
	sed -i -e "s|Virtual-1|$monname|g" dotconfig/waybar/config.jsonc
	sed -i -e "s|Virtual-1|$monname|g" dotconfig/waybar/modules.jsonc
	sed -i -e "s|Virtual-1|$monname|g" dotconfig/hypr/hyprland.conf
	sed -i -e "s|1920x1080|$monres|g" dotconfig/hypr/hyprland.conf
fi

#copies the files to their respective paths
cp -r dotconfig/* ~/.config/
cp -r doticons/* ~/.icons/
cp -r dotthemes/* ~/.themes/
cp -r Pictures/* ~/Pictures
cp -r shellscripts/* ~/shellscripts/

#attempting to setup YAY
cd ~/
git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -s --noconfirm && echo "$varpw" | sudo -S pacman -U *.pkg.tar.zst --noconfirm

cd ~/
rm -rf ~/yay-bin

#installs vesktop
echo "$varpw" | yay -S --noconfirm --needed Vesktop
#installs faugus
echo "$varpw" | yay -S --noconfirm --needed faugus-launcher

#installs neovim plugins
nvim +'PlugInstall --sync' +qa
echo "$nvimtext" >> ~/.config/nvim/init.vim



echo "Would like to have the system boot directly to hypr?(y/n)"
read locktog

if [ "$locktog" = "y" ]; then

	echo "$varpw" | sudo -S systemctl enable getty@tty1
	echo "$varpw" | sudo -S mkdir -p /etc/systemd/system/getty@tty1.service.d
	echo "$varpw" | sudo touch /etc/systemd/system/getty@tty1.service.d/override.conf
	echo "$varpw" | sudo -S tee /etc/systemd/system/getty@tty1.service.d/override.conf >/dev/null <<< "$gettytext"
	cp ~/$ricename/.zshrc ~/
	echo "$zshtext" >> ~/.zshrc
	echo "deleting unnecessary programs"
	echo ""
	echo "$varpw" | sudo -S pacman -R sddm dolphin --noconfirm
	rm -rf ~/$ricename
	echo "done.....system rebooting.....godspeed $USER.....godspeed"
	sleep 1
	echo 5
	sleep 1
	echo 4
	sleep 1
	echo 3
	sleep 1
	echo 2
	sleep 1
	echo 1
	sleep 1
	echo "$varpw" | sudo -S reboot

else

	cp ~/$ricename/.zshrc ~/
	cp ~/$ricename/post_install ~/
	echo done....check ~/post_install for instructions on how to bypass default login screen, the system will now reboot in 5 seconds
	rm -rf ~/$ricename
	sleep 5
	echo "$varpw" | sudo -S reboot

fi

#echo done
