splash = false

wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpapers/dlmb.jpg
    fit_mode = cover

}

wallpaper {
    monitor = DP-4
    path = ~/Pictures/Wallpapers/dlmb.jpg 
    fit_mode = cover

}
